% ser-2017-aha-slcs.Rnw

%---------------------------------------------------------------
% Preamble
% --------------------------------------------------------------
%
% NOTE: See rice-sample.tex written by Daina Chiba at Rice University for formatting and preamble code that I copied, http://ricebeamer.dynaman.net/
\documentclass[final]{beamer}
\usepackage[orientation=landscape, size=custom, width=121.92, height=106.68, scale=1.7]{beamerposter}  % this matches 4 feet (48 inches) by 3.5 feet (42 inches). Will get from phdposters.com 1 inch per 2.54 cm

\mode<presentation>{\usetheme{UNC5}}
\usepackage[english]{babel}
\usepackage[latin1]{inputenc}
\usepackage{bm}
\usepackage{blindtext}
\usepackage{scrextend}
\addtokomafont{labelinglabel}{\sffamily}
\usepackage{csquotes}
\usepackage{booktabs}

\setbeamercolor{bibliography entry title}{fg=black,bg=black}% see http://tex.stackexchange.com/questions/71352/beamer-undefined-color-local-structure
\setbeamertemplate{caption}[numbered]

% got from http://tex.stackexchange.com/questions/48023/mimic-bibtex-apalike-with-biblatex-biblatex-apa-broken
\PassOptionsToPackage{
        style=numeric,
        hyperref=true,
        backend=bibtex,
        maxbibnames=1,
        firstinits=true,
        uniquename=init,
        maxcitenames=2,
        parentracker=true,
        url=false,
        doi=true,
        isbn=false,
        eprint=false,
        backref=false,
            }{biblatex}
% see the following link for info on biblatex sort order issue: 
% http://tex.stackexchange.com/questions/51434/biblatex-citation-order
\usepackage[natbib=true, sorting=none, style=numeric, backend=biber]{biblatex}
\addbibresource{lit}
\renewcommand*{\bibfont}{\scriptsize}

%\usepackage{fontspec} % have to compile with XeLaTeX
%\setmainfont{Arial}
\usepackage[T1]{fontenc}
\usepackage{helvet}
\renewcommand{\familydefault}{\sfdefault} % get something like Arial

\usepackage{amsmath,amsthm, amssymb, latexsym}
\usepackage{wrapfig}


\usepackage{array,booktabs,tabularx}
\newcolumntype{Z}{>{\centering\arraybackslash}X} % centered tabularx columns

\usepackage[shortlabels]{enumitem}

% \setlist[description]{style=nextline}
\setlist[itemize]{leftmargin=0.55in, labelindent=16pt, label=$\bullet$}

\usepackage[framemethod=TikZ]{mdframed}
\mdfdefinestyle{MyFrame}{%
    linecolor=carolinablue,
    outerlinewidth=4pt,
    roundcorner=20pt,
    innerrightmargin=20pt,
    innerleftmargin=20pt,
    backgroundcolor=carolinablue!20}
    
% comment 
\newcommand{\comment}[1]{}

% (relative) path to the figures
\graphicspath{{figs/}}

\newlength{\columnheight}
\setlength{\columnheight}{105cm}
\newlength{\sepwid}
\newlength{\onecolwid}
\newlength{\twocolwid}
\newlength{\threecolwid}
\setlength{\sepwid}{0.024\paperwidth}
\setlength{\onecolwid}{0.31\paperwidth}
\setlength{\twocolwid}{0.31\paperwidth}
\setlength{\threecolwid}{0.31\paperwidth}



<<mainSettings, echo=FALSE, include=FALSE>>=

library(knitr)
library(data.table)
library(readxl)
library(ggplot2)
library(plyr)
library(ztable)
opts_chunk$set(echo=FALSE, comment=NA, message=FALSE, results='asis', cache=F)
opts_knit$set(root.dir="../slides")
@

% This is based on the template at http://www-i6.informatik.rwth-aachen.de/~dreuw/latexbeamerposter.php

% --------------------------------------------------------------------------------------% 
% Title, author, date, etc.
% --------------------------------------------------------------------------------------% 
% see http://tex.stackexchange.com/questions/9740/how-can-i-add-vertical-space-to-a-beamercolorbox-to-make-it-align-with-another-o
\title{Lipid-related Genetic Variants and Lipid Outcomes in a Cohort of Chilean Children} 
\author[vonholle@unc.edu]{Ann Von Holle, Anne Justice, Misa Graff, Kari North, UNC, Chapel Hill, NC; Estela Blanco, Sheila Gahagan, UCSD, San Diego, CA; B\'arbara Angel, Unidad de Nutrici\'on P\'ublica INTA, Univ de Chile, Santiago, Chile; Jos\'e Luis Santos, Pontificia Univ Cat\'olica de Chile, Santiago, Chile}
\institute{UNC}

% -------------------------------------------------------------------------------------%
% Contents
% -------------------------------------------------------------------------------------%

\begin{document}
\setlength{\parfillskip}{0pt plus 1fil}


\begin{frame}[t]

  \begin{columns}[T] % t instead of T or c means columns start at top

    % ---------------------------------------------------------%
    % Set up 1st column
    % ---------------------------------------------------------%
    \begin{column}{\onecolwid}
    \begin{beamercolorbox}[wd=\textwidth]{postercolumn}
    % fill each column with content
        % -----------------------------------------------------------
        % 1-1 (first column's first block
        % -----------------------------------------------------------
        % fill each column with content
        \begin{block}{Introduction}

Lipid concentrations:
          \begin{itemize}
                \begin{itemize} \normalsize
                    \item Are a recognized heritable risk factor for cardiovascular disease (CVD)
                    \item Associate with >150 loci in adults
                    \item Vary across ancestral groups
                    \item Include high density lipoprotein cholesterol (HDL-C), low density lipoprotein cholesterol (LDL-C) and triglycerides (TG).
                    \end{itemize}
            \item Genetic architecture underlying lipid traits is similar across ancestral groups for adults.
            \item Unclear if lipid-related loci associations found in adults extend to younger age groups. 
              \begin{itemize}\normalsize
                \item One European study establishes continuity of associations across the age spectrum, but no evidence exists in Hispanic/Latino populations.
                \end{itemize}
            \end{itemize}
    
        \end{block}
        \vskip1ex
    
        % -----------------------------------------------------------
        % 1-2
        % -----------------------------------------------------------
        \begin{block}{Aims}
        
        \setbeamertemplate{itemize items}[square]
        
        \begin{description}
            \item[Aim 1] Estimate association between lipid risk variants first identified in adults and adolescent lipid traits from Santiago Longitudinal Cohort Study (SLCS), a Chilean infancy cohort.
            \item[Aim 2] Compare results between SLCS and Cardiovascular Risk in Young Finns Study Cohort (CRYF).
            \end{description}

        \end{block}
        \vskip1ex

        % -----------------------------------------------------------
        % 1-3
        % -----------------------------------------------------------

        
        \begin{block}{Sample}
        
\vspace{-1em}
        
% see http://tex.stackexchange.com/questions/208429/problem-with-wrapfig-and-itemize
\begin{itemize}
    \parbox[t]{\dimexpr\textwidth-\leftmargin}{%
\raggedright
      \begin{wrapfigure}[10]{r}{0.4\textwidth}
        \centering
        \includegraphics[width=\linewidth]{santiago-map.png}
      \end{wrapfigure}
\normalsize{
          \item 1,645 infants began SLCS between 1991-1996
          \item \raggedright Current sample recruited from 2 of 3 randomized control trial groups (n=888)
          \item  n=677 with infancy and adolescent data and of those n=546 with genotyped data (platform: Multi-Ethnic Global Array (MEGA))
          \item Low to middle income status in Chile.
          \item Ancestrally mixed American Indian and Spanish descent families
          \item Lipid traits measured after overnight fasting at mean age 17 years.
          }
    }
  \end{itemize}

  \end{block}

  \end{beamercolorbox}
  \end{column}
    % ---------------------------------------------------------%
    % end the 1st column
    % ---------------------------------------------------------%

% ---------------------------------------------------------%
% Set up 2nd column
% ---------------------------------------------------------%

\begin{column}{\twocolwid}
\begin{beamercolorbox}[center,wd=\textwidth]{postercolumn}

        % -----------------------------------------------------------
        % 2-1
        % -----------------------------------------------------------
        \begin{block}{Methods}
        
        \begin{enumerate}[1.]
          \item Test additive association between lipid traits and adequately powered single risk variants.
            \begin{itemize} \normalsize
              \item 76 common \textbf{lipid variants} selected from a European genome-wide meta-analysis with strongest independent signal.
              \item Association tests include 6 \textbf{single variants} with \textit{a priori} power > 0.80.
            \end{itemize}
          \item Assess the association of weighted genetic risk scores (wGRS) on lipid traits using linear regression model.
       \begin{itemize} \normalsize
           \item \textbf{Coefficients} for wGRS and power calculations based on European adult association studies.
              \end{itemize}
          \item Characterize proportion of variance explained by lipid variants.
          \end{enumerate}
% \vskip0.5em
% \toprule[2mm]
% \vskip0.5em

        \end{block}
        \vskip1ex

        % -----------------------------------------------------------
        % 2-2
        % -----------------------------------------------------------
        \begin{block}{Results}
        
        % Point to code to make all tables from summary statistics run on Kure
        % These figures were originally made for Dec 2016 presentation
        

        <<code1, echo=F>>=
          read_chunk("../slides/tables-slides.R")
        @

        <<table1-1, results='hide'>>=
        @

\normalsize Table. Sample descriptive statistics
\resizebox{\linewidth}{!}{%
        <<>>=
          print(z, type="latex")
        @
        }
        
        % First figure
        % %%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%


        % Run code chunk from tables-slides.R to make table from summary statistics run on Kure

        <<assoc-1, results='hide'>>=
        @
        
        <<fig-assoc-1, results='hide'>>=
        @

\vskip0.75em

# Figure 1. Association tests by variant and sample
% NOTE: these were determined via power calculations at ~\Documents\dissertation\unc-dissertation-markdown\includes\scripts\power-calcs-ind-assoc.Rmd
        \centering
        \begin{figure}
%        \caption{Candidate single variant tests of association by variant and sample}

          <<fig-assoc-2-poster, fig.keep='last', fig.height=12, fig.width=15>>=
          @
        \end{figure}
        
            \begin{itemize}
            \item \raggedright Four of the seven association tests were nominally statistically significant.
              \end{itemize}



        \end{block}

\end{beamercolorbox}
\end{column}

% ---------------------------------------------------------%
% end the 2nd column


% ---------------------------------------------------------%
% Set up 3rd column
% ---------------------------------------------------------%

\begin{column}{\threecolwid}
\begin{beamercolorbox}[center,wd=\textwidth]{postercolumn}


        \vfill

        % -----------------------------------------------------------
        % 3-1
        % -----------------------------------------------------------
        \begin{block}{Results, cont...}
        
        
          
        % Second figure
        % %%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
        \centering
# Figure 2. wPRS regression coefficients by sample and sex

% Run code chunk from tables-slides.R to make table from summary statistics run on Kure

        <<fig3-1, results='hide'>>=
        @

        \begin{figure}
        <<fig3-2-poster, results='hide', fig.keep='last', fig.height=12, fig.width=20>>=
        @
        \end{figure}
        
        
\vspace{-0.4em}
        
        \begin{addmargin}[2cm]{0cm}
        \begin{flusChileaneft}
        \footnotesize{*Coefficients represent change in outcome per 1 SD change in wPRS, adjusted for first five principal components representing ancestry.}
        \end{flusChileaneft}
        \end{addmargin}
        
        \begin{itemize}
            \item \raggedright  wPRS has stronger association for each lipid outcome in Chilean versus Finnish sample except LDL-C for females.
            \end{itemize}
\vskip0.5em

        % Third figure
        % %%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%

% Run code chunk from tables-slides.R to make table from summary statistics run on Kure

        <<fig2-1, results='hide'>>=
        @
        

        # Figure 3. Proportion of lipid traits variance explained by lipid-related variants, by sex
        \centering
        \begin{figure}
          <<fig2-2poster, fig.keep='last', fig.height=11, fig.width=20>>=
          @
        \end{figure}

%        \begin{mdframed}[style=MyFrame]
          \begin{itemize}
            \item \raggedright LDL-C-related variants explain much less variance in Chilean sample.
            \end{itemize}
%            \end{mdframed}
        
        \end{block}
        
        \vskip1ex
        \vfill
        
        % -----------------------------------------------------------
        % 3-2
        % -----------------------------------------------------------
        \begin{block}{Summary}
        
          \begin{itemize}
            \item This study provides evidence that genetic architecture underlying lipid traits in a Chilean cohort is similar to that previously found in a Finnish cohort.
              \begin{itemize}
                \item LDL-C traits are an exception.
                \end{itemize}
            
            \end{itemize}
        \end{block}
        
        \vskip1ex
        \vfill


        % -----------------------------------------------------------
        % 3-3
        % -----------------------------------------------------------
        % \begin{block}{References}
        %   %\scriptsize{%          \printbibliography{}}
        %   \scriptsize
        %   (1) \fullcite{coram_genome-wide_2013} \\
        %   (2) \fullcite{lozoff_behavioral_2003} \\
        %   (3) \fullcite{tikkanen_association_2011} \\
        %   (4) \fullcite{teslovich_biological_2010} \\
        %   (5) \fullcite{buscot_combined_2016} \\
        %   % see https://en.wikibooks.org/wiki/LaTeX/Fonts
        % \end{block}

\end{beamercolorbox}
\end{column}
% ---------------------------------------------------------%
% end the 3rd column
% ---------------------------------------------------------%

\end{columns}

\end{frame}
\end{document}